project:
  type: website
  output-dir: _site

website:
  title: "MNA para Simuladores SPICE"
  site-url: "https://haulisson.github.io/SPICE-MNA/"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: mna/intro.qmd
        text: Fundamentos
      - href: mna/stamping.qmd
        text: Stamping
      - href: mna/examples.qmd
        text: Exemplos
      - href: mna/numerical.qmd
        text: Numérico

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    number-sections: true
    html-math-method: mathjax
    mermaid:
      theme: neutral

execute:
  freeze: auto
